### ISSUE TITLE
1.0 semver check not working properly

### ISSUE THREAD

**Issue by daffl** [bitrise-steplib/steps-npm#11]
For most npm valid Semver ranges (tested with `>=` and `^`), the 1.0.0 version returns the following error:

```
error reading npm version from package.json: package json content error: `>= 5.0.0` is not valid semver string: Malformed version: >= 5.0.0
```

**Comment by bitce** [comment]
Hi @daffl ! Thanks for your report, we're aware of the issue and working on the fix, should be released shortly!

**Comment by lszucs** [comment]
Hi @daffl,

We have just released a patch release which fixes build failures related to version constraints.

For more info, see: https://github.com/bitrise-steplib/steps-npm/releases/tag/1.0.1

For now, I'll close this issue, but if you need more info/help feel free to open a new issue!
