### ISSUE TITLE
1.0.1 semver check not working properly

### ISSUE THREAD

**Issue by mderrier** [bitrise-steplib/steps-npm#15]
For most npm valid Semver ranges with gap (tested with ||), the 1.0.1 version returns the following error:

`error reading npm version from package.json: package json content error: `5.x || 6.x` is not valid semver string: Malformed version: 5.x || 6.x`

**Comment by bitce** [comment]
Hi @mderrier ! If I'm correct this issue was fixed by the time you raised it, are you still experiencing it?

**Comment by mderrier** [comment]
Yes, I still having the semver problem with steps-npm@**1.0.1** (latest)
If I use
`"engines: {"npm": "^5.0.0 || ^6.4.0"}` from package.json
then
bitrise steps-npm throw this error:
`error reading npm version from package.json: package json content error: ^5.0.0 || ^6.0.0 is not valid semver string: Malformed version: ^5.0.0 || ^6.0.0`

I need to use this, because my dev machine use npm 6.x and prod use 5.x

**Comment by bitce** [comment]
Oh I see, sorry about that! Can you please include a build URL where you are experiencing this?
