### ISSUE TITLE
Newer versions don't show console output of npm commands

### ISSUE THREAD

**Issue by corymsmith** [bitrise-steplib/steps-npm#16]
When I'm running `0.9.1` I can see any linting errors and failed test output from the `npm test` command but after upgrading to `1.0.1` all I see is `Error running command test: error running npm command: exit status 1`.

It looks like it was changed in this commit: https://github.com/bitrise-steplib/steps-npm/commit/352a9478756aac77b9cfc1a2a7fcf5ccc57ce741

**Comment by BirmacherAkos** [comment]
Hi @corymsmith !

Sorry for the delayed answer.
The Tooling Team has an internal ticket about the issue and they will fix it.

Thanks for the issue report 🥇

**Comment by lszucs** [comment]
Hello @corymsmith,

We have released a patch version `1.0.2` to fix this. Thank you for reporting it!
