### ISSUE TITLE
npm update available for  1.1.0 

### ISSUE THREAD

**Issue by YunusHaas** [bitrise-steplib/steps-npm#20]
This version of NPM isn't being used locally or in my configuration. How am I supposed to resolve this build error?

| x | npm@1.0.2 (exit code: 1)                                      | 14.17 sec|
+---+---------------------------------------------------------------+----------+
| Update available: 1.0.2 -> 1.1.0                                             |
| Issue tracker: https://github.com/bitrise-steplib/steps-npm/issues           |
| Source: https://github.com/bitrise-steplib/steps-npm

**Comment by bitce** [comment]
Hi @YunusHaas can you update the step version?
