### ISSUE TITLE
Build fails due to missing package.json

### ISSUE THREAD

**Issue by rosenexpend** [bitrise-steplib/steps-npm#29]
While my build works well on my local simulator, my build currently fails due to missing package.json error on bitrise. I have seen several similar issues such as [this](https://github.com/bitrise-steplib/steps-npm/issues/8), raised but they seem to be old so I decided to post my error here as well to see if it can be resolved. My node version is 14.14.0, my npm version is 6.14.8, MacOS 10.15.7.

INFO[21:40:53] Step uses latest version -- Updating StepLib ... 
+------------------------------------------------------------------------------+

| (0) cache-pull                                                               |
+---+---------------------------------------------------------------+----------+
+---+---------------------------------------------------------------+----------+
| ✓ | cache-pull                                                    | 33.45 sec|
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+

| (1) npm                                                                      |
+---+---------------------------------------------------------------+----------+
+---+---------------------------------------------------------------+----------+
| ✓ | npm                                                           | 18.62 sec|
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+

| (2) npm                                                                      |
+------------------------------------------------------------------------------+
| id: npm                                                                      |
| version: 1.1.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-10-29T21:41:46Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- Workdir: /Users/vagrant/git
- Command: test
- NpmVersion: 
- UseCache: false
Autodetecting npm version
Checking package.json for npm version
No package.json found at path: /Users/vagrant/git/package.json
Could not read version information from package.json
Locating system installed npm
npm found at /usr/local/bin/npm
$ npm "--version"
system npm version: 6.14.8
Running user provided command
$ npm "test"
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/vagrant/git/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/vagrant/git/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vagrant/.npm/_logs/2020-10-29T21_41_48_706Z-debug.log
Error running command test: exit status 254

**Comment by bitce** [comment]
Hi @rosenexpend! Do you have a package.json file at the root of your repository?

**Comment by rosenexpend** [comment]
Hi @bitce. Yes, I have a package.json file in the root project directory. It turned out to be a change in the `bitrise.yml` that was not updated in this branch. I will close this issue now.
