### ISSUE TITLE
dyld: attempt to run simulator program outside simulator (DYLD_ROOT_PATH not set)

### ISSUE THREAD

**Issue by HabibAliAtFolio3** [bitrise-steplib/steps-npm#42]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.1.4
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES 

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Steps to reproduce

1. ...Here is the step
- npm@1:
        inputs:
        - workdir: "$BITRISE_SOURCE_DIR"
        - command: install
2. ..It throws error dyld: attempt to run simulator program outside simulator (DYLD_ROOT_PATH not set)
3. I remove this step, everything works fine

**Comment by Roland-Bak** [comment]
Hello there @HabibAliAtFolio3 👋

Can you please send us the log file or the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/ ) so that we can take a more in-depth look? 🙂
