### ISSUE TITLE
NPM step fails if project has an `.nvmrc` file

### ISSUE THREAD

**Issue by ga-reth** [bitrise-steplib/steps-npm#56]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.1.6
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? 

### Issue description

In our react native app folder we have an `.nvmrc` file specifying the node version, which causes the npm step to fail (logs below). 

Removing this file and instead specifying engine versions in `package.json` resolves the issue. 

From an initial investigation, it seems the VM is using `asdf` to manage / install versions, and that tool has issues with `.nvmrc` - see comment at the bottom of [this issue](https://github.com/asdf-vm/asdf/issues/914).

I have created a minimal repro

### Bitrise info

- Build URL:  https://app.bitrise.io/build/5986f86a-3aec-40c8-86bf-60a0eb0faabb
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: NO but can add if needs be
- Log: 

<details>
  <pre>
Config:
- workdir: /Users/vagrant/git
- command: install
- npm_version: <unset>
- cache_local_deps: false
Info: From npm version >= v5.7.0, you can use the `npm ci` command insead of `npm install`. Using this command might speeds up your workflow.
It does not work without `package-lock.json` so please commit it into the VCS repository. More info: https://github.com/npm/npm/releases/tag/v5.7.0
Autodetecting npm version
Checking package.json for npm version
Ensuring npm version 8.19.3
$ npm "install" "-g" "--force" "npm@8.19.3"
Install dependencies: failed to install npm version `8.19.3`: npm command failed: 
Install dependencies: failed to install npm version `8.19.3`: npm command failed: 
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Run npm command (Failed)                                      | 1.66 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-npm/issues           |
| Source: https://github.com/bitrise-steplib/steps-npm                         |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

### Steps to reproduce

I have created a minimal repro that is just a fresh react native project with an `.nvmrc` file, if you remove the `.nvmrc` file the step passes. 

https://github.com/garethveale/rn-bitrise-issue

**Comment by sandeharsa** [comment]
I am also having this issue in my project.

I just want to add that I first encountered this after the change to M1 machines. My last successful build was on an Intel machine, even with a `.nvmrc` file.

**Comment by alaughlin** [comment]
Also experiencing this problem. `.nvmrc` is pretty vital to ensuring that all devs are working off the same version of node locally, so removing this file from our repositories is not option.

**Comment by ga-reth** [comment]
bump ^^

**Comment by mickaeldanslenowhere** [comment]
I solve the issue by running a script after cloning the repo
I just run rm .nvmrc
As I don't push back to git, it doesn't impact our devex
