### ISSUE TITLE
npm ERR! Test failed

### ISSUE THREAD

**Issue by BologaMarius** [bitrise-steplib/steps-npm#6]
Running test locally the test runs without no problem, but when bitrise tries to run the test I get the following error:
 
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: node::(anonymous namespace)::ContextifyScript::RunInContext(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
 6: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 7: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 8: 0x26f978b842fd
 9: 0x26f978c3d1d6
sh: line 1:  1651 Abort trap: 6           npm run test:api
npm ERR! Test failed.  See above for more details.

npm version: 6.4.1
node version: v10.11.0

**Comment by bitce** [comment]
Hi @BologaMarius could you please send us a build URL we could take a look at regarding this issue?

**Comment by BologaMarius** [comment]
Hi @bitce here is the URL: https://app.bitrise.io/build/d4896bfa5ff9d283

**Comment by fehersanyi-bitrise** [comment]
Hy @BologaMarius I am afraid that I don't understand the error, what is the script that you are trying to run here?
